USE master
GO

CREATE DATABASE CCFEU_DB
	ON  
	(	NAME = N'CCFEU_DB', 
		FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CCFEU_DB.mdf', 
		SIZE = 8192KB , 
		MAXSIZE = UNLIMITED, 
		FILEGROWTH = 65536KB 
	)
	LOG ON 
	(	NAME = N'CCFEU_DB_log', 
		FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CCFEU_DB_log.ldf' , 
		SIZE = 8192KB , 
		MAXSIZE = 2048GB , 
		FILEGROWTH = 65536KB 
	)
	WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

